/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionariosIdRouteImport } from './routes/funcionarios.$id'

const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosIdRoute = FuncionariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FuncionariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRouteWithChildren
  '/registrar': typeof RegistrarRoute
  '/relatorio': typeof RelatorioRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRouteWithChildren
  '/registrar': typeof RegistrarRoute
  '/relatorio': typeof RelatorioRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRouteWithChildren
  '/registrar': typeof RegistrarRoute
  '/relatorio': typeof RelatorioRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/funcionarios'
    | '/registrar'
    | '/relatorio'
    | '/funcionarios/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/funcionarios' | '/registrar' | '/relatorio' | '/funcionarios/$id'
  id:
    | '__root__'
    | '/'
    | '/funcionarios'
    | '/registrar'
    | '/relatorio'
    | '/funcionarios/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FuncionariosRoute: typeof FuncionariosRouteWithChildren
  RegistrarRoute: typeof RegistrarRoute
  RelatorioRoute: typeof RelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios/$id': {
      id: '/funcionarios/$id'
      path: '/$id'
      fullPath: '/funcionarios/$id'
      preLoaderRoute: typeof FuncionariosIdRouteImport
      parentRoute: typeof FuncionariosRoute
    }
  }
}

interface FuncionariosRouteChildren {
  FuncionariosIdRoute: typeof FuncionariosIdRoute
}

const FuncionariosRouteChildren: FuncionariosRouteChildren = {
  FuncionariosIdRoute: FuncionariosIdRoute,
}

const FuncionariosRouteWithChildren = FuncionariosRoute._addFileChildren(
  FuncionariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FuncionariosRoute: FuncionariosRouteWithChildren,
  RegistrarRoute: RegistrarRoute,
  RelatorioRoute: RelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
