/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as PorDiaRouteImport } from './routes/por-dia'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as IntegracaoRouteImport } from './routes/integracao'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ArmazenamentoRouteImport } from './routes/armazenamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionariosIdRouteImport } from './routes/funcionarios.$id'
import { Route as ApiPublicRhMarmitasRouteImport } from './routes/api/public/rh/marmitas'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PorDiaRoute = PorDiaRouteImport.update({
  id: '/por-dia',
  path: '/por-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracaoRoute = IntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmazenamentoRoute = ArmazenamentoRouteImport.update({
  id: '/armazenamento',
  path: '/armazenamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosIdRoute = FuncionariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FuncionariosRoute,
} as any)
const ApiPublicRhMarmitasRoute = ApiPublicRhMarmitasRouteImport.update({
  id: '/api/public/rh/marmitas',
  path: '/api/public/rh/marmitas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/auditoria': typeof AuditoriaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRouteWithChildren
  '/integracao': typeof IntegracaoRoute
  '/permissoes': typeof PermissoesRoute
  '/por-dia': typeof PorDiaRoute
  '/registrar': typeof RegistrarRoute
  '/relatorio': typeof RelatorioRoute
  '/seguranca': typeof SegurancaRoute
  '/usuarios': typeof UsuariosRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
  '/api/public/rh/marmitas': typeof ApiPublicRhMarmitasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/auditoria': typeof AuditoriaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRouteWithChildren
  '/integracao': typeof IntegracaoRoute
  '/permissoes': typeof PermissoesRoute
  '/por-dia': typeof PorDiaRoute
  '/registrar': typeof RegistrarRoute
  '/relatorio': typeof RelatorioRoute
  '/seguranca': typeof SegurancaRoute
  '/usuarios': typeof UsuariosRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
  '/api/public/rh/marmitas': typeof ApiPublicRhMarmitasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armazenamento': typeof ArmazenamentoRoute
  '/auditoria': typeof AuditoriaRoute
  '/fornecedores': typeof FornecedoresRoute
  '/funcionarios': typeof FuncionariosRouteWithChildren
  '/integracao': typeof IntegracaoRoute
  '/permissoes': typeof PermissoesRoute
  '/por-dia': typeof PorDiaRoute
  '/registrar': typeof RegistrarRoute
  '/relatorio': typeof RelatorioRoute
  '/seguranca': typeof SegurancaRoute
  '/usuarios': typeof UsuariosRoute
  '/funcionarios/$id': typeof FuncionariosIdRoute
  '/api/public/rh/marmitas': typeof ApiPublicRhMarmitasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/armazenamento'
    | '/auditoria'
    | '/fornecedores'
    | '/funcionarios'
    | '/integracao'
    | '/permissoes'
    | '/por-dia'
    | '/registrar'
    | '/relatorio'
    | '/seguranca'
    | '/usuarios'
    | '/funcionarios/$id'
    | '/api/public/rh/marmitas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/armazenamento'
    | '/auditoria'
    | '/fornecedores'
    | '/funcionarios'
    | '/integracao'
    | '/permissoes'
    | '/por-dia'
    | '/registrar'
    | '/relatorio'
    | '/seguranca'
    | '/usuarios'
    | '/funcionarios/$id'
    | '/api/public/rh/marmitas'
  id:
    | '__root__'
    | '/'
    | '/armazenamento'
    | '/auditoria'
    | '/fornecedores'
    | '/funcionarios'
    | '/integracao'
    | '/permissoes'
    | '/por-dia'
    | '/registrar'
    | '/relatorio'
    | '/seguranca'
    | '/usuarios'
    | '/funcionarios/$id'
    | '/api/public/rh/marmitas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmazenamentoRoute: typeof ArmazenamentoRoute
  AuditoriaRoute: typeof AuditoriaRoute
  FornecedoresRoute: typeof FornecedoresRoute
  FuncionariosRoute: typeof FuncionariosRouteWithChildren
  IntegracaoRoute: typeof IntegracaoRoute
  PermissoesRoute: typeof PermissoesRoute
  PorDiaRoute: typeof PorDiaRoute
  RegistrarRoute: typeof RegistrarRoute
  RelatorioRoute: typeof RelatorioRoute
  SegurancaRoute: typeof SegurancaRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiPublicRhMarmitasRoute: typeof ApiPublicRhMarmitasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-dia': {
      id: '/por-dia'
      path: '/por-dia'
      fullPath: '/por-dia'
      preLoaderRoute: typeof PorDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracao': {
      id: '/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof IntegracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armazenamento': {
      id: '/armazenamento'
      path: '/armazenamento'
      fullPath: '/armazenamento'
      preLoaderRoute: typeof ArmazenamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios/$id': {
      id: '/funcionarios/$id'
      path: '/$id'
      fullPath: '/funcionarios/$id'
      preLoaderRoute: typeof FuncionariosIdRouteImport
      parentRoute: typeof FuncionariosRoute
    }
    '/api/public/rh/marmitas': {
      id: '/api/public/rh/marmitas'
      path: '/api/public/rh/marmitas'
      fullPath: '/api/public/rh/marmitas'
      preLoaderRoute: typeof ApiPublicRhMarmitasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FuncionariosRouteChildren {
  FuncionariosIdRoute: typeof FuncionariosIdRoute
}

const FuncionariosRouteChildren: FuncionariosRouteChildren = {
  FuncionariosIdRoute: FuncionariosIdRoute,
}

const FuncionariosRouteWithChildren = FuncionariosRoute._addFileChildren(
  FuncionariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmazenamentoRoute: ArmazenamentoRoute,
  AuditoriaRoute: AuditoriaRoute,
  FornecedoresRoute: FornecedoresRoute,
  FuncionariosRoute: FuncionariosRouteWithChildren,
  IntegracaoRoute: IntegracaoRoute,
  PermissoesRoute: PermissoesRoute,
  PorDiaRoute: PorDiaRoute,
  RegistrarRoute: RegistrarRoute,
  RelatorioRoute: RelatorioRoute,
  SegurancaRoute: SegurancaRoute,
  UsuariosRoute: UsuariosRoute,
  ApiPublicRhMarmitasRoute: ApiPublicRhMarmitasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
